
import { ContentItem } from '../types';

export const getGoogleCalendarUrl = (item: ContentItem, subjectCode: string = ''): string => {
  const baseUrl = 'https://www.google.com/calendar/render?action=TEMPLATE';
  
  const title = encodeURIComponent(`[${subjectCode}] ${item.title}`);
  
  const description = encodeURIComponent(
    `Academic Alert from Semester Saviours\n\n` +
    `Subject: ${subjectCode}\n` +
    `Type: ${item.type.toUpperCase()}\n` +
    `Details: ${item.content}\n\n` +
    `Contributed by: ${item.uploaderId}\n` +
    `Generated by Semester Saviours AI`
  );

  if (!item.deadlineDate) return '';
  
  const dateStr = item.deadlineDate.replace(/-/g, '');
  const start = `${dateStr}T090000Z`;
  const end = `${dateStr}T100000Z`;
  const dates = `${start}/${end}`;

  return `${baseUrl}&text=${title}&details=${description}&dates=${dates}`;
};

export const downloadIcsFile = (item: ContentItem, subjectCode: string = '') => {
  if (!item.deadlineDate) return;

  const dateStr = item.deadlineDate.replace(/-/g, '');
  const start = `${dateStr}T090000Z`;
  const end = `${dateStr}T100000Z`;

  const icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Semester Saviours//Academic Portal//EN',
    'BEGIN:VEVENT',
    `SUMMARY:[${subjectCode}] ${item.title}`,
    `DTSTART:${start}`,
    `DTEND:${end}`,
    `DESCRIPTION:${item.content.replace(/\n/g, '\\n')}`,
    'STATUS:CONFIRMED',
    'SEQUENCE:0',
    'BEGIN:VALARM',
    'TRIGGER:-PT24H', 
    'ACTION:DISPLAY',
    'DESCRIPTION:Reminder',
    'END:VALARM',
    'END:VEVENT',
    'END:VCALENDAR'
  ].join('\r\n');

  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `${item.title.replace(/\s+/g, '_')}.ics`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
